version: '3.8'
services:
  app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - mongo
      - kafka
    environment:
      - KAFKA_BROKERS=localhost:9092

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=andrewvb2012
      - MONGO_INITDB_ROOT_PASSWORD=U3aQdGnoYzznB1d2

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
